# Book settings
title: Programmeren
author: Hanze University of Applied Sciences
logo: images/mascot.png
copyright: ""
exclude_patterns: ["LICENSE.md", "README.md"]

latex:
  latex_documents:
    targetname: book.tex
html:
  home_page_in_navbar : true
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: true
  navbar_number_sections : false
  baseurl : "https://misja.github.io/programmeren/"  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/
  # google_analytics_id: UA-11111111 # add your Google Analytics Tracking Code
  comments:
    hypothesis: true
    utterances:
      repo: "misja/programmeren"
  extra_footer : |
      <div>
      <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/"><img src="https://licensebuttons.net/l/by-nc-sa/3.0/88x31.png"></a>
          Alle inhoud op deze site (tenzij anders vermeld) valt onder de <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a> licentie.
      </div>

launch_buttons:
  notebook_interface : "jupyterlab"
  binderhub_url      : "https://mybinder.org"
  thebe              : true

repository:
  url          : https://github.com/misja/programmeren
  path_to_book : ""
  branch       : master

sphinx:
  config:
    html_show_copyright: false
    myst_admonition_enable: true
    myst_deflist_enable: true
